Add configurable minimum permissions for triggers
jenkinsci/github-pr-comment-build-plugin pull request #60
Opened 2023-03-03 14:27 UTC by pascal-hofmann

This allows to set the minimum permissions required for triggering builds. 
E.g. when set to admin only comments/changes/reviews by admins trigger builds.

![Bildschirm­foto 2023-03-03 um 15 26 31](https://user-images.githubusercontent.com/2102878/222745589-463823a1-9d9a-4ff7-abf9-2ebedbb39770.png)

2023-03-03 23:54 UTC, lprimak commented
@pascal-hofmann I am not sure I understand any reason for this change.
The "allow untrusted builds" no longer makes any sense, and creates a combinatorial explosion
with the dropdown box which makes no sense and is very confusing.

For example, "NONE" equals "allow untrusted builds" and wording is confusing.
"READ" makes no sense to me because if there are no "READ" permissions, the user wouldn't
be able to clone nor comment on the PR anyway.
"ADMIN" *may* make sense but it's really a stretch, I can't think of a single use case for it.

Am I not understanding something critical here?
What's the exact issue that triggered the need for this change?
Can you create a ticket that explains the issue in detail?

2023-03-03 23:57 UTC, lprimak requested changes
See comments on this PR. It doesn't make sense to me

2023-03-03 23:58 UTC, lprimak commented on src/main/java/com/adobe/jenkins/github_pr_comment_build/TriggerPRReviewBranchProperty.java
> +         * Populates the strategy options.
Repeated code. Needs refactor

2023-03-04 10:58 UTC, pascal-hofmann commented
Hi, 
thanks for the quick and honest feedback. I'll create an issue with more details and will also update this PR.

2023-03-04 11:28 UTC, pascal-hofmann commented
@lprimak I updated the PR description to make the intent/reasoning behind this PR clearer.

2023-03-04 17:39 UTC, lprimak commented
Ok, I can see the issue with private repositories.
I think your solution should work and not break anything.
Please create a ticket nonetheless (you can delete the template if you wish)

2023-03-05 10:43 UTC, pascal-hofmann commented
I opened https://github.com/jenkinsci/github-pr-comment-build-plugin/issues/61 for this.

2023-03-16 01:44 UTC, lprimak commented
@pascal-hofmann I already reviewed it (repeated code comments, etc)
I realize there is already repeated code, but I would rather not have any more repeated code on top of that.
Thank you

2023-03-16 08:16 UTC, pascal-hofmann commented
@lprimak I just tried creating an abstract base class `AbstractTriggerBranchProperty` but I can also see this as selectable in the jenkins UI. Do you know how to get rid of this?

2023-03-16 16:44 UTC, pascal-hofmann commented
I‘m not sure what will happen with existing configurations if I do that. I thought this way things just continue to work as expected. If that’s not desired I can remove it completely.

What do you prefer?

2023-04-14 14:04 UTC, pascal-hofmann commented
Hey,
is there any update on this? Can I help with getting this merged?

2023-04-17 18:09 UTC, bluesliverx commented
I'm just trying to get the PR to build and then I'll merge. Also, there is a new label type that was just barely merged. I'll work on getting this same functionality added to that after it builds/merges. Unless you beat me to it and then by all means add it to the label trigger (#62) @pascal-hofmann

2023-04-17 18:16 UTC, merged

2023-04-17 18:49 UTC, bluesliverx commented
This has been released in 96.v9ff13b69dd66.